=== FreeFallingRN/abd-companion/data/schemas/chapter.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Chapter",
  "type": "object",
  "required": [
    "chapterNumber",
    "title",
    "arcId",
    "arcName"
  ],
  "properties": {
    "chapterNumber": {
      "type": "integer",
      "minimum": 1
    },
    "title": {
      "type": "string"
    },
    "arcId": {
      "type": "string"
    },
    "arcName": {
      "type": "string"
    },
    "file": {
      "type": "string"
    }
  }
}

=== FreeFallingRN/abd-companion/data/chapters.json
[
  {
    "chapterNumber": 1,
    "title": "Chapter 1: Nonsense Battle",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter0.html"
  },
  {
    "chapterNumber": 2,
    "title": "Chapter 2: Another World",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter1.html"
  },
  {
    "chapterNumber": 3,
    "title": "Chapter 3: Soul",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter2.html"
  },
  {
    "chapterNumber": 4,
    "title": "Chapter 4: \u2019House\u2019 but a Home",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter3.html"
  },
  {
    "chapterNumber": 5,
    "title": "Chapter 5: The Trial",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter4.html"
  },
  {
    "chapterNumber": 6,
    "title": "Chapter 6: The Results",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter5.html"
  },
  {
    "chapterNumber": 7,
    "title": "Chapter 7: Beast Dominion",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter6.html"
  },
  {
    "chapterNumber": 8,
    "title": "Chapter 8: Beast Selection",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter7.html"
  },
  {
    "chapterNumber": 9,
    "title": "Chapter 9: Cat",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter8.html"
  },
  {
    "chapterNumber": 10,
    "title": "Chapter 10: Weapon and Pet",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter9.html"
  },
  {
    "chapterNumber": 11,
    "title": "Chapter 11: First Kill",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter10.html"
  },
  {
    "chapterNumber": 12,
    "title": "Chapter 12: Level 1",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter11.html"
  },
  {
    "chapterNumber": 13,
    "title": "Chapter 13: Stat Upgrade",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter12.html"
  },
  {
    "chapterNumber": 14,
    "title": "Chapter 14: Soul Crystal!",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter13.html"
  },
  {
    "chapterNumber": 15,
    "title": "Chapter 15: Beast & Blade Emporium",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter14.html"
  },
  {
    "chapterNumber": 16,
    "title": "Chapter 16: Hunters",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter15.html"
  },
  {
    "chapterNumber": 17,
    "title": "Chapter 17: Trash",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter16.html"
  },
  {
    "chapterNumber": 18,
    "title": "Chapter 18: Party",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter17.html"
  },
  {
    "chapterNumber": 19,
    "title": "Chapter 19: Merry Time",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter18.html"
  },
  {
    "chapterNumber": 20,
    "title": "Chapter 20: Conditioning A Cat",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter19.html"
  },
  {
    "chapterNumber": 21,
    "title": "Chapter 21: Green Light",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter20.html"
  },
  {
    "chapterNumber": 22,
    "title": "Chapter 22: Butler",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter21.html"
  },
  {
    "chapterNumber": 23,
    "title": "Chapter 23: Butler Butcher",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter22.html"
  },
  {
    "chapterNumber": 24,
    "title": "Chapter 24: Level Up!",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter23.html"
  },
  {
    "chapterNumber": 25,
    "title": "Chapter 25: Sera\u2019s Culinary",
    "arcId": "arc_1_awakening",
    "arcName": "Phase I: Kendru Outskirts & Awakening",
    "file": "OEBPS/chapter24.html"
  },
  {
    "chapterNumber": 26,
    "title": "Chapter 26: System\u2019s Suggestion",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter25.html"
  },
  {
    "chapterNumber": 27,
    "title": "Chapter 27: Spirit Caller",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter26.html"
  },
  {
    "chapterNumber": 28,
    "title": "Chapter 28: Yandere! (Slight R18)",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter27.html"
  },
  {
    "chapterNumber": 29,
    "title": "Chapter 29: Confessions (Slight R18)",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter28.html"
  },
  {
    "chapterNumber": 30,
    "title": "Chapter 30: Crack In Smile",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter29.html"
  },
  {
    "chapterNumber": 31,
    "title": "Chapter 31: Growing Strong",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter30.html"
  },
  {
    "chapterNumber": 32,
    "title": "Chapter 32: Blood Bond!",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter31.html"
  },
  {
    "chapterNumber": 33,
    "title": "Chapter 33: Ticking Nuke (Slight R18)",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter32.html"
  },
  {
    "chapterNumber": 34,
    "title": "Chapter 34: Give Me Your Baby~ (R18)",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter33.html"
  },
  {
    "chapterNumber": 35,
    "title": "Chapter 35: Imperial Notice",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter34.html"
  },
  {
    "chapterNumber": 36,
    "title": "Chapter 36: Snakes",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter35.html"
  },
  {
    "chapterNumber": 37,
    "title": "Chapter 37: Purged Nest",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter36.html"
  },
  {
    "chapterNumber": 38,
    "title": "Chapter 38: Dryad!",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter37.html"
  },
  {
    "chapterNumber": 39,
    "title": "Chapter 39: Spiritual Space",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter38.html"
  },
  {
    "chapterNumber": 40,
    "title": "Chapter 40: Spiritual Island!",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter39.html"
  },
  {
    "chapterNumber": 41,
    "title": "Chapter 41: Uneasiness",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter40.html"
  },
  {
    "chapterNumber": 42,
    "title": "Chapter 42: One Shot",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter41.html"
  },
  {
    "chapterNumber": 43,
    "title": "Chapter 43: Manure",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter42.html"
  },
  {
    "chapterNumber": 44,
    "title": "Chapter 44: Baron",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter43.html"
  },
  {
    "chapterNumber": 45,
    "title": "Chapter 45: Discussions",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter44.html"
  },
  {
    "chapterNumber": 46,
    "title": "Chapter 46: Spanking The Baron",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter45.html"
  },
  {
    "chapterNumber": 47,
    "title": "Chapter 47: The Bloom of Power",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter46.html"
  },
  {
    "chapterNumber": 48,
    "title": "Chapter 48: Night Guest",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter47.html"
  },
  {
    "chapterNumber": 49,
    "title": "Chapter 49: Annoying Pests",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
    "file": "OEBPS/chapter48.html"
  },
  {
    "chapterNumber": 50,
    "title": "Chapter 50: Freeloader? Ain\u2019t No More",
    "arcId": "arc_2_aurelius",
    "arcName": "Phase II: Aurelius Beast Academy Entrance",
